# Site settings
title: YAPB
description: "Yet Another Personal Blog..."
url:  "https://henyihanwobushi.github.io/" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Dongsheng Hong"
  email: "henyihanwobushi@gmail.com"
  url: "https://henyihanwobushi.github.io/"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 10
paginate_path: "/page:num/"

#SEO
ogo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://github.com/henyihanwobushi
    - https://www.linkedin.com/in/henyihanwobushi/'
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never